services:
  postgres:
    image: postgres:16
    container_name: PLpgSQL
    restart: always
    environment:
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: 24081499
      POSTGRES_DB: smartHome
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgUser"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - smart_home_network

  smart_home_app:
    build: .
    container_name: smart_home_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartHome
      SPRING_DATASOURCE_USERNAME: pgUser
      SPRING_DATASOURCE_PASSWORD: 24081499
    ports:
      - "8085:8085"
    networks:
      - smart_home_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Упрощаем setup для разработки
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk_network

  kibana:
      image: docker.elastic.co/kibana/kibana:8.9.0
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"
      networks:
        - elk_network

  logstash:
      image: docker.elastic.co/logstash/logstash:8.9.0
      depends_on:
        - elasticsearch
      volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      ports:
        - "5001:5001" # Порт для приема логов от приложений
      networks:
        - elk_network
      command: logstash -f /usr/share/logstash/pipeline/logstash.conf

networks:
  smart_home_network:
    driver: bridge

  elk_network:
    driver: bridge

volumes:
  pg_data:

  elasticsearch_data:
